#!/usr/bin/env python3
"""
Ancestry Independence Test for Walker Noise Floor Regression (Experiment 5)

Tests whether the Edge Jaccard regression (noise_floor ~ 1.243 * jaccard - 0.721)
from Experiment 4 generalizes to topology pairs that share NO derivation history
with each other or with the Open grid.

CRITICAL DESIGN CONSTRAINT: No variant is generated by modifying the Open grid's
edge set. Every variant is constructed from scratch on the same 100-room 10x10
positional grid. Rooms occupy the same (row, col) positions. Only the connections
are independently generated.

Phase 1: 5 independent-vs-Open pairs
Phase 2: 10 independent-vs-independent pairs
Phase 3: Regression comparison with statistical tests
Phase 4: Prediction error distribution

Single new file. Outputs to output_ancestry_independence/.
"""

import os
import random
from itertools import combinations

import numpy as np
import networkx as nx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats as scipy_stats

# ---------------------------------------------------------------------------
# Import pipeline functions AS-IS
# ---------------------------------------------------------------------------
from mud_behavior_heatmaps import (
    SEED, GRID_ROWS, GRID_COLS,
    room_id, room_coords,
    build_open_grid,
    compute_visit_heatmap,
)
from mud_behavior_normalized import (
    BASELINE_SEED, BASELINE_SESSIONS,
    generate_random_walk_baseline,
    compute_residual, compute_correlation,
)
from mud_calibration_test import (
    CALIBRATION_SEED,
    generate_walker_sessions,
)
from mud_topology_sensitivity import (
    edge_jaccard,
    build_variant_a, build_variant_b, build_variant_c,
    build_variant_d, build_variant_e,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
OUTPUT_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "output_ancestry_independence"
)

# Original Experiment 4 regression coefficients
EXP4_SLOPE = 1.243
EXP4_INTERCEPT = -0.721
EXP4_R_SQ = 0.572

# Experiment 4 variant labels
EXP4_VARIANT_NAMES = ["A_open", "B_mild", "C_river", "D_maze", "E_hub"]
EXP4_SHORT_LABELS = ["A", "B", "C", "D", "E"]

# Independent variant labels
INDEP_VARIANT_NAMES = [
    "F_prob_card", "G_radius2", "H_span_rewire", "I_watts_strog", "J_config"
]
INDEP_SHORT_LABELS = ["F", "G", "H", "I", "J"]
INDEP_FULL_LABELS = [
    "F (Prob. Cardinal)", "G (Radius-2 Geom.)",
    "H (Span+Rewire)", "I (Watts-Strogatz)", "J (Config. Model)"
]


def save_fig(fig, name):
    path = os.path.join(OUTPUT_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"    Saved: {path}")


# ===================================================================
# Independent Topology Variant Builders
# ===================================================================

def _ensure_bidirectional(G):
    """Make all edges bidirectional."""
    for u, v in list(G.edges()):
        if not G.has_edge(v, u):
            G.add_edge(v, u)


def _add_node_positions(G):
    """Add pos attribute to all nodes."""
    for n in G.nodes():
        r, c = room_coords(n)
        G.nodes[n]["pos"] = (c, GRID_ROWS - 1 - r)


def _ensure_connected_cardinal(G, rng):
    """If G is disconnected (as undirected), add minimum cardinal edges to connect.

    Only adds edges between cardinal-adjacent rooms (Manhattan distance 1).
    """
    G_undir = G.to_undirected()
    components = list(nx.connected_components(G_undir))
    if len(components) <= 1:
        return

    # Build list of all possible cardinal edges between different components
    comp_map = {}
    for ci, comp in enumerate(components):
        for node in comp:
            comp_map[node] = ci

    # Use union-find approach: greedily add cardinal edges to merge components
    parent = list(range(len(components)))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        px, py = find(x), find(y)
        if px != py:
            parent[px] = py
            return True
        return False

    # Collect all potential cardinal bridge edges
    bridge_candidates = []
    for r in range(GRID_ROWS):
        for c in range(GRID_COLS):
            n = room_id(r, c)
            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if 0 <= nr < GRID_ROWS and 0 <= nc < GRID_COLS:
                    m = room_id(nr, nc)
                    if comp_map[n] != comp_map[m]:
                        bridge_candidates.append((n, m))

    rng.shuffle(bridge_candidates)
    for u, v in bridge_candidates:
        cu, cv = comp_map[u], comp_map[v]
        if union(cu, cv):
            G.add_edge(u, v)
            G.add_edge(v, u)


def build_variant_f():
    """Variant F: Probabilistic Cardinal Grid.

    For each ~360 cardinal adjacency, include with p=0.80 (seed 700).
    Connectivity repair with minimum cardinal edges. No non-cardinal shortcuts.
    """
    rng = random.Random(700)
    G = nx.DiGraph()
    for n in range(100):
        r, c = room_coords(n)
        G.add_node(n, pos=(c, GRID_ROWS - 1 - r))

    # Enumerate all cardinal adjacencies and include with probability 0.80
    for r in range(GRID_ROWS):
        for c in range(GRID_COLS):
            n = room_id(r, c)
            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if 0 <= nr < GRID_ROWS and 0 <= nc < GRID_COLS:
                    m = room_id(nr, nc)
                    if rng.random() < 0.80:
                        G.add_edge(n, m)

    _ensure_bidirectional(G)
    _ensure_connected_cardinal(G, rng)
    assert G.number_of_nodes() == 100
    assert nx.is_strongly_connected(G), "Variant F not strongly connected"
    return G


def build_variant_g():
    """Variant G: Radius-2 Geometric Graph.

    Connect all pairs within Manhattan distance <= 2. Then randomly remove edges
    (seed 701) until avg out-degree ~4.0, preserving connectivity.
    """
    rng = random.Random(701)
    G = nx.DiGraph()
    for n in range(100):
        r, c = room_coords(n)
        G.add_node(n, pos=(c, GRID_ROWS - 1 - r))

    # Add all distance-<=2 edges
    for r1 in range(GRID_ROWS):
        for c1 in range(GRID_COLS):
            n1 = room_id(r1, c1)
            for r2 in range(GRID_ROWS):
                for c2 in range(GRID_COLS):
                    if r1 == r2 and c1 == c2:
                        continue
                    if abs(r1 - r2) + abs(c1 - c2) <= 2:
                        n2 = room_id(r2, c2)
                        G.add_edge(n1, n2)

    # Trim: randomly remove edges until avg out-degree ~4.0
    target_degree = 4.0
    target_edges = int(target_degree * 100)  # 400 directed edges

    # Collect undirected edge pairs for removal
    undirected_edges = set()
    for u, v in G.edges():
        undirected_edges.add((min(u, v), max(u, v)))
    edge_list = list(undirected_edges)
    rng.shuffle(edge_list)

    for u, v in edge_list:
        if G.number_of_edges() <= target_edges:
            break
        # Don't create degree-0 nodes or break connectivity
        if G.out_degree(u) > 2 and G.out_degree(v) > 2:
            G.remove_edge(u, v)
            G.remove_edge(v, u)
            if not nx.is_strongly_connected(G):
                G.add_edge(u, v)
                G.add_edge(v, u)

    assert G.number_of_nodes() == 100
    assert nx.is_strongly_connected(G), "Variant G not strongly connected"
    return G


def _wilsons_algorithm(nodes, rng):
    """Generate a uniform random spanning tree using Wilson's algorithm.

    Returns a list of (u, v) undirected edges forming the tree.
    """
    n = len(nodes)
    node_set = set(nodes)
    # Build adjacency: fully connected (any node can reach any other)
    in_tree = set()
    tree_edges = []

    # Start with a random root
    root = rng.choice(nodes)
    in_tree.add(root)

    remaining = list(node_set - in_tree)
    rng.shuffle(remaining)

    for start in remaining:
        if start in in_tree:
            continue

        # Random walk from start until hitting the tree
        path = [start]
        current = start
        visited_in_walk = {start: 0}

        while current not in in_tree:
            # Choose random neighbor (any other node — complete graph)
            next_node = rng.choice(nodes)
            while next_node == current:
                next_node = rng.choice(nodes)

            if next_node in visited_in_walk:
                # Loop erasure: remove the cycle
                loop_start = visited_in_walk[next_node]
                # Remove entries from visited_in_walk for erased nodes
                for erased in path[loop_start + 1:]:
                    del visited_in_walk[erased]
                path = path[:loop_start + 1]
                current = next_node
            else:
                path.append(next_node)
                visited_in_walk[next_node] = len(path) - 1
                current = next_node

        # Add path to tree
        for i in range(len(path) - 1):
            tree_edges.append((path[i], path[i + 1]))
            in_tree.add(path[i])
        # The last node in path is already in tree
        in_tree.add(path[-1])

    return tree_edges


def build_variant_h():
    """Variant H: Spanning Tree + Random Rewiring.

    Wilson's algorithm (seed 702) for uniform random spanning tree.
    Add 150 random edges (seed 703). Target ~250 total edges.
    """
    nodes = list(range(100))

    # Wilson's algorithm for spanning tree
    rng_tree = random.Random(702)
    tree_edges = _wilsons_algorithm(nodes, rng_tree)

    G = nx.DiGraph()
    for n in nodes:
        r, c = room_coords(n)
        G.add_node(n, pos=(c, GRID_ROWS - 1 - r))

    for u, v in tree_edges:
        G.add_edge(u, v)
        G.add_edge(v, u)

    # Add 150 random edges
    rng_rewire = random.Random(703)
    added = 0
    attempts = 0
    while added < 150 and attempts < 10000:
        u = rng_rewire.randint(0, 99)
        v = rng_rewire.randint(0, 99)
        if u != v and not G.has_edge(u, v):
            G.add_edge(u, v)
            G.add_edge(v, u)
            added += 1
        attempts += 1

    assert G.number_of_nodes() == 100
    assert nx.is_strongly_connected(G), "Variant H not strongly connected"
    return G


def build_variant_i():
    """Variant I: Watts-Strogatz Small World.

    Ring topology (row-major order), K=3 nearest neighbors on each side,
    rewire with beta=0.25 (seed 704).
    """
    rng = random.Random(704)
    n = 100
    k_each_side = 3  # 6 connections per node

    G = nx.DiGraph()
    for node in range(n):
        r, c = room_coords(node)
        G.add_node(node, pos=(c, GRID_ROWS - 1 - r))

    # Ring: connect each node to K=3 nearest neighbors on each side
    for i in range(n):
        for j in range(1, k_each_side + 1):
            neighbor = (i + j) % n
            G.add_edge(i, neighbor)
            G.add_edge(neighbor, i)

    # Rewire with probability beta=0.25
    beta = 0.25
    edges_to_rewire = list(G.edges())
    rng.shuffle(edges_to_rewire)

    for u, v in edges_to_rewire:
        if rng.random() < beta:
            if not G.has_edge(u, v):
                continue
            # Rewire: keep u, change v to random node
            candidates = [x for x in range(n) if x != u and not G.has_edge(u, x)]
            if candidates:
                new_v = rng.choice(candidates)
                G.remove_edge(u, v)
                if G.has_edge(v, u) and G.out_degree(v) > 1:
                    G.remove_edge(v, u)
                G.add_edge(u, new_v)
                G.add_edge(new_v, u)

    _ensure_bidirectional(G)

    # Ensure connectivity
    if not nx.is_strongly_connected(G):
        _ensure_connected_cardinal(G, rng)

    assert G.number_of_nodes() == 100
    assert nx.is_strongly_connected(G), "Variant I not strongly connected"
    return G


def build_variant_j():
    """Variant J: Degree-Matched Random Graph (Configuration Model).

    Take Open's exact degree sequence. Generate random graph with same
    degree sequence using configuration model (seed 705).
    Resolve multi-edges/self-loops via edge swaps. Ensure connectivity.
    """
    rng = random.Random(705)
    np_rng = np.random.RandomState(705)

    G_open = build_variant_a()
    degree_seq = sorted([G_open.out_degree(n) for n in range(100)], reverse=True)

    # Use networkx configuration model on undirected graph
    # (since we want bidirectional edges, work with undirected then convert)
    # Ensure even sum
    if sum(degree_seq) % 2 != 0:
        degree_seq[0] += 1

    # Generate using configuration model with repeated attempts
    for attempt in range(50):
        try:
            G_undir = nx.configuration_model(degree_seq, seed=705 + attempt)
            # Remove self-loops and parallel edges
            G_undir = nx.Graph(G_undir)
            G_undir.remove_edges_from(nx.selfloop_edges(G_undir))
            break
        except nx.NetworkXError:
            continue

    # Build directed graph
    G = nx.DiGraph()
    for n in range(100):
        r, c = room_coords(n)
        G.add_node(n, pos=(c, GRID_ROWS - 1 - r))

    for u, v in G_undir.edges():
        if u < 100 and v < 100:
            G.add_edge(u, v)
            G.add_edge(v, u)

    # Ensure connectivity via edge swaps
    if not nx.is_strongly_connected(G):
        G_test = G.to_undirected()
        components = list(nx.connected_components(G_test))
        while len(components) > 1:
            # Pick two components and bridge them
            c1 = list(components[0])
            c2 = list(components[1])
            n1 = rng.choice(c1)
            n2 = rng.choice(c2)

            # Add bridge edge
            G.add_edge(n1, n2)
            G.add_edge(n2, n1)

            # Try to remove a random edge from the larger component to preserve degree
            c_large = c1 if len(c1) > len(c2) else c2
            edges_in_large = [(u, v) for u, v in G.edges()
                              if u in set(c_large) and v in set(c_large)
                              and G.out_degree(u) > 2 and G.out_degree(v) > 2]
            if edges_in_large:
                eu, ev = rng.choice(edges_in_large)
                G.remove_edge(eu, ev)
                if G.has_edge(ev, eu):
                    G.remove_edge(ev, eu)
                if not nx.is_strongly_connected(G):
                    G.add_edge(eu, ev)
                    G.add_edge(ev, eu)

            G_test = G.to_undirected()
            components = list(nx.connected_components(G_test))

    assert G.number_of_nodes() == 100
    assert nx.is_strongly_connected(G), "Variant J not strongly connected"
    return G


# ===================================================================
# Main
# ===================================================================

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print("=" * 78)
    print("MUD BEHAVIORAL HEATMAP — ANCESTRY INDEPENDENCE TEST (Experiment 5)")
    print("=" * 78)

    # ------------------------------------------------------------------
    # Step 1: Build all topology variants (Exp4 originals + independent)
    # ------------------------------------------------------------------
    print("\n[1] Building topology variants...")
    print("  [1a] Experiment 4 originals (ancestry-sharing)...")

    exp4_variants = {
        "A_open": build_variant_a(),
        "B_mild": build_variant_b(),
        "C_river": build_variant_c(),
        "D_maze": build_variant_d(),
        "E_hub": build_variant_e(),
    }
    for name in EXP4_VARIANT_NAMES:
        G = exp4_variants[name]
        avg_deg = np.mean([G.out_degree(n) for n in G.nodes()])
        print(f"    {name:<14s}: {G.number_of_edges()} edges, "
              f"avg out-degree={avg_deg:.2f}")

    print("  [1b] Independent variants (no shared ancestry)...")
    indep_builders = {
        "F_prob_card": build_variant_f,
        "G_radius2": build_variant_g,
        "H_span_rewire": build_variant_h,
        "I_watts_strog": build_variant_i,
        "J_config": build_variant_j,
    }
    indep_variants = {}
    for name, builder in indep_builders.items():
        G = builder()
        indep_variants[name] = G
        avg_deg = np.mean([G.out_degree(n) for n in G.nodes()])
        print(f"    {name:<14s}: {G.number_of_edges()} edges, "
              f"avg out-degree={avg_deg:.2f}")

    # ------------------------------------------------------------------
    # Step 2: Pre-compute per-variant data
    # ------------------------------------------------------------------
    print("\n[2] Pre-computing baselines and Walker sessions...")

    all_variants = {}
    all_variants.update(exp4_variants)
    all_variants.update(indep_variants)

    baselines = {}
    walker_heatmaps = {}

    all_names = EXP4_VARIANT_NAMES + INDEP_VARIANT_NAMES

    for name in all_names:
        G = all_variants[name]
        print(f"  {name:<14s}: baseline...", end="", flush=True)
        baselines[name] = generate_random_walk_baseline(
            G, BASELINE_SESSIONS, BASELINE_SEED)
        print(" walker...", end="", flush=True)
        sessions = generate_walker_sessions(G, name, CALIBRATION_SEED)
        raw = compute_visit_heatmap(sessions, "walker")
        walker_heatmaps[name] = compute_residual(raw, baselines[name])
        print(" done.")

    # ------------------------------------------------------------------
    # Step 3: Reproduce Experiment 4 training pairs
    # ------------------------------------------------------------------
    print("\n[3] Reproducing Experiment 4 training pairs (10 pairs)...")

    exp4_pairs = list(combinations(range(5), 2))
    exp4_jaccard = []
    exp4_noise_floor = []
    exp4_labels = []

    for i, j in exp4_pairs:
        name_i = EXP4_VARIANT_NAMES[i]
        name_j = EXP4_VARIANT_NAMES[j]
        label = f"{EXP4_SHORT_LABELS[i]}-{EXP4_SHORT_LABELS[j]}"

        jac = edge_jaccard(all_variants[name_i], all_variants[name_j])
        nf = compute_correlation(
            walker_heatmaps[name_i], walker_heatmaps[name_j], set())

        exp4_jaccard.append(jac)
        exp4_noise_floor.append(nf)
        exp4_labels.append(label)
        print(f"  {label:<6s}: Jaccard={jac:.4f}, noise_floor={nf:.4f}")

    exp4_jaccard = np.array(exp4_jaccard)
    exp4_noise_floor = np.array(exp4_noise_floor)

    # Refit Experiment 4 regression to get exact coefficients from this run
    slope4, intercept4, r4, p4, se4 = scipy_stats.linregress(
        exp4_jaccard, exp4_noise_floor)
    r_sq4 = r4 ** 2
    pred4 = slope4 * exp4_jaccard + intercept4
    rmse4 = np.sqrt(np.mean((exp4_noise_floor - pred4) ** 2))

    print(f"\n  Refit Exp4 regression: noise_floor = {slope4:.3f} * jaccard "
          f"+ {intercept4:.3f}")
    print(f"  R^2 = {r_sq4:.4f}, RMSE = {rmse4:.4f}")

    # ------------------------------------------------------------------
    # Phase 1: Independent-vs-Open Pairs (5 pairs)
    # ------------------------------------------------------------------
    print("\n[4] Phase 1: Independent-vs-Open Pairs (5 pairs)...")

    phase1_jaccard = []
    phase1_noise_floor = []
    phase1_labels = []

    for idx, name in enumerate(INDEP_VARIANT_NAMES):
        label = f"A-{INDEP_SHORT_LABELS[idx]}"
        jac = edge_jaccard(all_variants["A_open"], all_variants[name])
        nf = compute_correlation(
            walker_heatmaps["A_open"], walker_heatmaps[name], set())

        phase1_jaccard.append(jac)
        phase1_noise_floor.append(nf)
        phase1_labels.append(label)
        print(f"  {label:<6s}: Jaccard={jac:.4f}, noise_floor={nf:.4f}")

    phase1_jaccard = np.array(phase1_jaccard)
    phase1_noise_floor = np.array(phase1_noise_floor)

    # ------------------------------------------------------------------
    # Phase 2: Independent-vs-Independent Pairs (10 pairs)
    # ------------------------------------------------------------------
    print("\n[5] Phase 2: Independent-vs-Independent Pairs (10 pairs)...")

    indep_pairs = list(combinations(range(5), 2))
    phase2_jaccard = []
    phase2_noise_floor = []
    phase2_labels = []

    for i, j in indep_pairs:
        name_i = INDEP_VARIANT_NAMES[i]
        name_j = INDEP_VARIANT_NAMES[j]
        label = f"{INDEP_SHORT_LABELS[i]}-{INDEP_SHORT_LABELS[j]}"

        jac = edge_jaccard(all_variants[name_i], all_variants[name_j])
        nf = compute_correlation(
            walker_heatmaps[name_i], walker_heatmaps[name_j], set())

        phase2_jaccard.append(jac)
        phase2_noise_floor.append(nf)
        phase2_labels.append(label)
        print(f"  {label:<6s}: Jaccard={jac:.4f}, noise_floor={nf:.4f}")

    phase2_jaccard = np.array(phase2_jaccard)
    phase2_noise_floor = np.array(phase2_noise_floor)

    # ------------------------------------------------------------------
    # Phase 3: Regression Comparison and Statistical Tests
    # ------------------------------------------------------------------
    print("\n[6] Phase 3: Regression Comparison...")

    # Combine all independent pairs
    indep_jaccard = np.concatenate([phase1_jaccard, phase2_jaccard])
    indep_noise_floor = np.concatenate([phase1_noise_floor, phase2_noise_floor])
    indep_labels = phase1_labels + phase2_labels

    # Pooled data (all 25 pairs)
    pooled_jaccard = np.concatenate([exp4_jaccard, indep_jaccard])
    pooled_noise_floor = np.concatenate([exp4_noise_floor, indep_noise_floor])

    # Refit pooled regression
    slope_p, intercept_p, r_p, p_p, se_p = scipy_stats.linregress(
        pooled_jaccard, pooled_noise_floor)
    r_sq_p = r_p ** 2
    pred_p = slope_p * pooled_jaccard + intercept_p
    rmse_p = np.sqrt(np.mean((pooled_noise_floor - pred_p) ** 2))

    # Compute residuals from original Exp4 regression for independent pairs
    pred_indep = slope4 * indep_jaccard + intercept4
    residuals_indep = indep_noise_floor - pred_indep

    # Compute residuals from original Exp4 regression for training pairs
    residuals_train = exp4_noise_floor - pred4

    # --- Test 1: Systematic bias (one-sample t-test on residuals) ---
    t_bias, p_bias = scipy_stats.ttest_1samp(residuals_indep, 0)
    mean_resid_indep = np.mean(residuals_indep)

    # --- Test 2: Variance inflation (Levene's test) ---
    levene_stat, p_levene = scipy_stats.levene(residuals_train, residuals_indep)
    var_train = np.var(residuals_train, ddof=1)
    var_indep = np.var(residuals_indep, ddof=1)

    # --- Test 3: R^2 comparison (already computed above) ---

    # --- Test 4: Ancestry interaction test ---
    # noise_floor = b1*jaccard + b2*ancestry + b3*jaccard*ancestry + intercept
    # ancestry = 1 if either variant derives from Open, 0 otherwise
    ancestry_exp4 = np.ones(len(exp4_jaccard))     # All derive from Open
    ancestry_phase1 = np.ones(len(phase1_jaccard))  # Paired with Open
    ancestry_phase2 = np.zeros(len(phase2_jaccard))  # Neither derives from Open

    all_jac = pooled_jaccard
    all_nf = pooled_noise_floor
    all_ancestry = np.concatenate([ancestry_exp4, ancestry_phase1, ancestry_phase2])
    all_interaction = all_jac * all_ancestry

    # Multiple regression: nf = b0 + b1*jac + b2*ancestry + b3*jac*ancestry
    X = np.column_stack([
        np.ones(len(all_jac)),
        all_jac,
        all_ancestry,
        all_interaction,
    ])
    # OLS: beta = (X'X)^-1 X'y
    XtX = X.T @ X
    Xty = X.T @ all_nf
    try:
        beta = np.linalg.solve(XtX, Xty)
    except np.linalg.LinAlgError:
        beta = np.linalg.lstsq(X, all_nf, rcond=None)[0]

    y_pred_interact = X @ beta
    ss_res = np.sum((all_nf - y_pred_interact) ** 2)
    ss_tot = np.sum((all_nf - np.mean(all_nf)) ** 2)
    r_sq_interact = 1 - ss_res / ss_tot if ss_tot > 0 else 0.0

    n_obs = len(all_nf)
    k_params = 4
    dof = n_obs - k_params
    mse = ss_res / dof if dof > 0 else 0.0
    try:
        se_beta = np.sqrt(np.diag(mse * np.linalg.inv(XtX)))
    except np.linalg.LinAlgError:
        se_beta = np.full(k_params, np.nan)
    t_stats = beta / (se_beta + 1e-15)
    p_vals = 2 * (1 - scipy_stats.t.cdf(np.abs(t_stats), dof))

    param_names = ["Intercept", "Jaccard", "Ancestry", "Jaccard x Ancestry"]

    # Prediction errors
    pred_error_train = np.abs(residuals_train)
    pred_error_indep = np.abs(residuals_indep)

    # ------------------------------------------------------------------
    # Print Regression Comparison Table
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("REGRESSION COMPARISON TABLE")
    print("=" * 60)
    print(f"  {'Metric':<20s} {'Original (N=10)':>18s} {'Pooled (N=25)':>18s}")
    print(f"  {'-'*20} {'-'*18} {'-'*18}")
    print(f"  {'R^2':<20s} {r_sq4:>18.4f} {r_sq_p:>18.4f}")
    print(f"  {'Slope':<20s} {slope4:>18.4f} {slope_p:>18.4f}")
    print(f"  {'Intercept':<20s} {intercept4:>18.4f} {intercept_p:>18.4f}")
    print(f"  {'RMSE':<20s} {rmse4:>18.4f} {rmse_p:>18.4f}")
    print(f"  {'p-value (slope)':<20s} {p4:>18.4f} {p_p:>18.4f}")

    r_sq_change = r_sq_p - r_sq4
    print(f"\n  R^2 change: {r_sq_change:+.4f} "
          f"({'improved' if r_sq_change > 0 else 'degraded'})")

    # ------------------------------------------------------------------
    # Print Statistical Tests
    # ------------------------------------------------------------------
    print("\n" + "=" * 60)
    print("STATISTICAL TESTS")
    print("=" * 60)

    print(f"\n  Test 1: Systematic Bias (one-sample t-test on residuals)")
    print(f"    Mean residual (independent):  {mean_resid_indep:+.4f}")
    print(f"    Mean residual (training):     {np.mean(residuals_train):+.4f}")
    print(f"    t-statistic:                  {t_bias:.4f}")
    print(f"    p-value:                      {p_bias:.4f}")
    print(f"    Significant (p < 0.05):       "
          f"{'YES — ancestry-dependent bias' if p_bias < 0.05 else 'NO — no systematic bias'}")

    print(f"\n  Test 2: Variance Inflation (Levene's test)")
    print(f"    Variance (training):          {var_train:.6f}")
    print(f"    Variance (independent):       {var_indep:.6f}")
    print(f"    Variance ratio:               {var_indep / var_train:.2f}x"
          if var_train > 0 else "    Variance ratio:               N/A")
    print(f"    Levene statistic:             {levene_stat:.4f}")
    print(f"    p-value:                      {p_levene:.4f}")
    print(f"    Significant (p < 0.05):       "
          f"{'YES — variance inflated' if p_levene < 0.05 else 'NO — similar variance'}")

    print(f"\n  Test 4: Ancestry Interaction Regression")
    print(f"    noise_floor = b0 + b1*jaccard + b2*ancestry + b3*jaccard*ancestry")
    print(f"    R^2 = {r_sq_interact:.4f}")
    print(f"\n    {'Parameter':<22s} {'Coeff':>8s} {'Std.Err':>8s} "
          f"{'t-stat':>8s} {'p-value':>8s} {'Sig.':>6s}")
    print(f"    {'-'*22} {'-'*8} {'-'*8} {'-'*8} {'-'*8} {'-'*6}")
    for k in range(k_params):
        sig = "*" if p_vals[k] < 0.05 else ""
        print(f"    {param_names[k]:<22s} {beta[k]:>8.4f} {se_beta[k]:>8.4f} "
              f"{t_stats[k]:>8.4f} {p_vals[k]:>8.4f} {sig:>6s}")

    ancestry_significant = p_vals[2] < 0.05 or p_vals[3] < 0.05
    print(f"\n    Ancestry modulates Jaccard->noise floor: "
          f"{'YES' if ancestry_significant else 'NO'}")

    # ==================================================================
    # VISUALIZATION 1: Independent Topology Grid Visualization (5 panels)
    # ==================================================================
    print("\n[7] Generating visualizations...")
    print("  [7.1] Independent topology visualizations...")

    fig, axes = plt.subplots(1, 5, figsize=(30, 6))

    # Compute global max degree across independent variants
    global_max_deg = max(
        max(G.out_degree(n) for n in G.nodes())
        for G in indep_variants.values()
    )

    for idx, (name, label) in enumerate(
            zip(INDEP_VARIANT_NAMES, INDEP_FULL_LABELS)):
        ax = axes[idx]
        G = indep_variants[name]

        # Draw connections
        for u, v in G.edges():
            r1, c1 = room_coords(u)
            r2, c2 = room_coords(v)
            dist = abs(r1 - r2) + abs(c1 - c2)
            if dist > 2:
                ax.plot([c1, c2], [r1, r2], color="#3498db",
                        linewidth=0.5, alpha=0.3, linestyle="--")
            elif dist > 1:
                ax.plot([c1, c2], [r1, r2], color="#e67e22",
                        linewidth=0.5, alpha=0.4, linestyle=":")
            else:
                ax.plot([c1, c2], [r1, r2], color="#bdc3c7",
                        linewidth=0.4, alpha=0.5)

        # Draw rooms colored by out-degree
        for r in range(GRID_ROWS):
            for c in range(GRID_COLS):
                n = room_id(r, c)
                deg = G.out_degree(n)
                color = plt.cm.YlOrRd(deg / max(global_max_deg, 1))
                ax.add_patch(plt.Circle((c, r), 0.3, color=color,
                             edgecolor="black", linewidth=0.5, zorder=5))

        avg_deg = np.mean([G.out_degree(n) for n in G.nodes()])
        jac_with_open = edge_jaccard(all_variants["A_open"], G)
        ax.set_title(f"{label}\n{G.number_of_edges()} edges, "
                     f"avg deg={avg_deg:.1f}\nJaccard w/ Open={jac_with_open:.3f}",
                     fontsize=10, fontweight="bold")
        ax.set_xlim(-0.7, GRID_COLS - 0.3)
        ax.set_ylim(GRID_ROWS - 0.3, -0.7)
        ax.set_aspect("equal")
        ax.set_xticks(range(GRID_COLS))
        ax.set_yticks(range(GRID_ROWS))
        ax.tick_params(labelsize=6)
        ax.grid(True, alpha=0.1)

    sm = plt.cm.ScalarMappable(
        cmap="YlOrRd", norm=plt.Normalize(vmin=0, vmax=global_max_deg))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.tolist(), shrink=0.6, aspect=20, pad=0.02)
    cbar.set_label("Out-degree (exits)", fontsize=10)

    fig.suptitle("Independent Topology Variants (No Shared Ancestry with Open)\n"
                 "All variants: 100 rooms at same grid positions, "
                 "connections generated from scratch",
                 fontsize=14, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 0.95, 0.88])
    save_fig(fig, "01_independent_topologies.png")

    # ==================================================================
    # VISUALIZATION 2: Jaccard vs Noise Floor Scatter (Money Plot)
    # ==================================================================
    print("  [7.2] Jaccard vs. Noise Floor scatter (money plot)...")

    fig, ax = plt.subplots(figsize=(12, 8))

    # Plot training pairs (Exp4)
    ax.scatter(exp4_jaccard, exp4_noise_floor, s=100, c="#2c3e50",
               marker="o", zorder=5, edgecolors="white", linewidths=0.8,
               label=f"Exp4 training (N={len(exp4_jaccard)})")
    for pi, label in enumerate(exp4_labels):
        ax.annotate(label, (exp4_jaccard[pi], exp4_noise_floor[pi]),
                    textcoords="offset points", xytext=(6, 6),
                    fontsize=7, color="#2c3e50", alpha=0.8)

    # Plot Phase 1 (independent-vs-Open)
    ax.scatter(phase1_jaccard, phase1_noise_floor, s=120, c="#e74c3c",
               marker="^", zorder=6, edgecolors="white", linewidths=0.8,
               label=f"Independent vs Open (N={len(phase1_jaccard)})")
    for pi, label in enumerate(phase1_labels):
        ax.annotate(label, (phase1_jaccard[pi], phase1_noise_floor[pi]),
                    textcoords="offset points", xytext=(6, 6),
                    fontsize=7, color="#e74c3c", alpha=0.8)

    # Plot Phase 2 (independent-vs-independent)
    ax.scatter(phase2_jaccard, phase2_noise_floor, s=120, c="#27ae60",
               marker="s", zorder=6, edgecolors="white", linewidths=0.8,
               label=f"Independent vs Independent (N={len(phase2_jaccard)})")
    for pi, label in enumerate(phase2_labels):
        ax.annotate(label, (phase2_jaccard[pi], phase2_noise_floor[pi]),
                    textcoords="offset points", xytext=(6, 6),
                    fontsize=7, color="#27ae60", alpha=0.8)

    # Overlay original Exp4 regression line
    x_range = np.linspace(0, max(pooled_jaccard.max(), 1.0) + 0.05, 200)
    y_exp4 = slope4 * x_range + intercept4
    ax.plot(x_range, y_exp4, color="#2c3e50", linewidth=2, linestyle="--",
            alpha=0.7, label=f"Exp4 fit: y={slope4:.3f}x{intercept4:+.3f} "
                             f"(R\u00b2={r_sq4:.3f})")

    # Overlay pooled regression line
    y_pooled = slope_p * x_range + intercept_p
    ax.plot(x_range, y_pooled, color="#8e44ad", linewidth=2, linestyle="-",
            alpha=0.7, label=f"Pooled fit: y={slope_p:.3f}x{intercept_p:+.3f} "
                             f"(R\u00b2={r_sq_p:.3f})")

    ax.set_xlabel("Edge Jaccard Similarity", fontsize=12)
    ax.set_ylabel("Walker Noise Floor (Pearson r)", fontsize=12)
    ax.set_title("Ancestry Independence Test: Edge Jaccard vs. Walker Noise Floor\n"
                 "Do independent topology pairs fall on the same regression line?",
                 fontsize=13, fontweight="bold")
    ax.legend(loc="upper left", fontsize=9, framealpha=0.9)
    ax.grid(True, alpha=0.3)
    ax.axhline(y=0, color="gray", linewidth=0.5, alpha=0.5)

    # Annotate R^2 change
    ax.text(0.98, 0.05,
            f"R\u00b2 change: {r_sq4:.3f} \u2192 {r_sq_p:.3f} ({r_sq_change:+.3f})\n"
            f"Bias test p={p_bias:.3f}, Levene p={p_levene:.3f}",
            transform=ax.transAxes, fontsize=9, ha="right",
            bbox=dict(boxstyle="round", facecolor="lightyellow", alpha=0.8))

    plt.tight_layout()
    save_fig(fig, "02_jaccard_vs_noisefloor_scatter.png")

    # ==================================================================
    # VISUALIZATION 3: Prediction Error Distribution
    # ==================================================================
    print("  [7.3] Prediction error distribution...")

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Side-by-side histograms
    ax1 = axes[0]
    bins = np.linspace(0, max(pred_error_train.max(), pred_error_indep.max()) + 0.02, 15)
    ax1.hist(pred_error_train, bins=bins, alpha=0.6, color="#2c3e50",
             edgecolor="white", label=f"Training (N={len(pred_error_train)})")
    ax1.hist(pred_error_indep, bins=bins, alpha=0.6, color="#e74c3c",
             edgecolor="white", label=f"Independent (N={len(pred_error_indep)})")
    ax1.axvline(np.mean(pred_error_train), color="#2c3e50",
                linestyle="--", linewidth=2, alpha=0.7,
                label=f"Train mean={np.mean(pred_error_train):.3f}")
    ax1.axvline(np.mean(pred_error_indep), color="#e74c3c",
                linestyle="--", linewidth=2, alpha=0.7,
                label=f"Indep mean={np.mean(pred_error_indep):.3f}")
    ax1.set_xlabel("|Predicted - Actual| Noise Floor", fontsize=11)
    ax1.set_ylabel("Count", fontsize=11)
    ax1.set_title("Prediction Error Distribution\n(Histograms)", fontsize=12,
                  fontweight="bold")
    ax1.legend(fontsize=8, loc="upper right")
    ax1.text(0.98, 0.55, f"Levene's test\np = {p_levene:.4f}",
             transform=ax1.transAxes, fontsize=10, ha="right",
             bbox=dict(boxstyle="round", facecolor="lightyellow", alpha=0.8))

    # KDE overlay
    ax2 = axes[1]
    if len(pred_error_train) > 1 and np.std(pred_error_train) > 1e-10:
        kde_x = np.linspace(0, max(pred_error_train.max(),
                                   pred_error_indep.max()) + 0.05, 200)
        try:
            kde_train = scipy_stats.gaussian_kde(pred_error_train)
            ax2.plot(kde_x, kde_train(kde_x), color="#2c3e50", linewidth=2,
                     label="Training pairs")
            ax2.fill_between(kde_x, kde_train(kde_x), alpha=0.2, color="#2c3e50")
        except np.linalg.LinAlgError:
            ax2.hist(pred_error_train, bins=10, alpha=0.4, color="#2c3e50",
                     density=True, label="Training pairs")

    if len(pred_error_indep) > 1 and np.std(pred_error_indep) > 1e-10:
        kde_x = np.linspace(0, max(pred_error_train.max(),
                                   pred_error_indep.max()) + 0.05, 200)
        try:
            kde_indep = scipy_stats.gaussian_kde(pred_error_indep)
            ax2.plot(kde_x, kde_indep(kde_x), color="#e74c3c", linewidth=2,
                     label="Independent pairs")
            ax2.fill_between(kde_x, kde_indep(kde_x), alpha=0.2, color="#e74c3c")
        except np.linalg.LinAlgError:
            ax2.hist(pred_error_indep, bins=10, alpha=0.4, color="#e74c3c",
                     density=True, label="Independent pairs")

    ax2.set_xlabel("|Predicted - Actual| Noise Floor", fontsize=11)
    ax2.set_ylabel("Density", fontsize=11)
    ax2.set_title("Prediction Error Distribution\n(KDE overlay)", fontsize=12,
                  fontweight="bold")
    ax2.legend(fontsize=9, loc="upper right")
    ax2.text(0.98, 0.55, f"Levene's test\np = {p_levene:.4f}",
             transform=ax2.transAxes, fontsize=10, ha="right",
             bbox=dict(boxstyle="round", facecolor="lightyellow", alpha=0.8))

    fig.suptitle("Does the Exp4 Regression Generalize? Prediction Error Comparison",
                 fontsize=13, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 1, 0.92])
    save_fig(fig, "03_prediction_error_distribution.png")

    # ==================================================================
    # WRITTEN SUMMARY
    # ==================================================================
    print("\n" + "=" * 78)
    print("EXPERIMENT 5 — ANCESTRY INDEPENDENCE TEST: SUMMARY")
    print("=" * 78)

    # Determine outcome
    bias_detected = p_bias < 0.05
    variance_inflated = p_levene < 0.05
    r_sq_collapsed = r_sq_p < 0.40
    r_sq_held = r_sq_p >= r_sq4 * 0.8  # Within 20% of original

    print(f"\n  DATA SUMMARY:")
    print(f"    Training pairs (Exp4, shared ancestry):    {len(exp4_jaccard)}")
    print(f"    Independent-vs-Open pairs (Phase 1):       {len(phase1_jaccard)}")
    print(f"    Independent-vs-Independent pairs (Phase 2): {len(phase2_jaccard)}")
    print(f"    Total pairs:                               "
          f"{len(pooled_jaccard)}")

    print(f"\n  REGRESSION FIT:")
    print(f"    Original Exp4: R^2={r_sq4:.4f}, slope={slope4:.4f}, "
          f"intercept={intercept4:.4f}")
    print(f"    Pooled (N=25): R^2={r_sq_p:.4f}, slope={slope_p:.4f}, "
          f"intercept={intercept_p:.4f}")
    print(f"    R^2 change:    {r_sq_change:+.4f}")

    print(f"\n  STATISTICAL TESTS:")
    print(f"    Systematic bias:    mean_resid={mean_resid_indep:+.4f}, "
          f"p={p_bias:.4f} — {'SIGNIFICANT' if bias_detected else 'not significant'}")
    print(f"    Variance inflation: ratio={var_indep/var_train:.2f}x, "
          f"p={p_levene:.4f} — {'SIGNIFICANT' if variance_inflated else 'not significant'}"
          if var_train > 0 else
          f"    Variance inflation: N/A")
    print(f"    Ancestry interaction: "
          f"{'SIGNIFICANT' if ancestry_significant else 'not significant'}")

    # Determine which outcome
    if not bias_detected and not variance_inflated and not r_sq_collapsed:
        outcome = "GENERALIZES"
        print(f"\n  OUTCOME: REGRESSION GENERALIZES")
        print(f"    Independent pairs fall on the same line as training pairs.")
        print(f"    No systematic bias (p={p_bias:.3f}), no variance inflation "
              f"(p={p_levene:.3f}).")
        if r_sq_held:
            print(f"    R^2 {'improved' if r_sq_change > 0 else 'held'} "
                  f"({r_sq4:.3f} -> {r_sq_p:.3f}).")
        print(f"    Ancestry was NOT a confound in Experiment 4.")
        print(f"    The Edge Jaccard regression can be used for ANY topology pair:")
        print(f"      noise_floor = {slope_p:.4f} * jaccard + {intercept_p:.4f}")
    elif bias_detected and not r_sq_collapsed:
        outcome = "BIASED_BUT_CORRECTABLE"
        print(f"\n  OUTCOME: REGRESSION IS BIASED BUT CORRECTABLE")
        print(f"    Independent pairs show systematic offset "
              f"(mean resid = {mean_resid_indep:+.4f}).")
        print(f"    The relationship exists but coefficients need updating.")
        print(f"    Corrected (pooled) model:")
        print(f"      noise_floor = {slope_p:.4f} * jaccard + {intercept_p:.4f}")
        print(f"    Pooled R^2 = {r_sq_p:.4f}")
    else:
        outcome = "DOES_NOT_GENERALIZE"
        print(f"\n  OUTCOME: REGRESSION DOES NOT GENERALIZE")
        print(f"    Independent pairs scatter widely away from the training fit.")
        if r_sq_collapsed:
            print(f"    R^2 collapsed: {r_sq4:.3f} -> {r_sq_p:.3f}")
        if bias_detected:
            print(f"    Systematic bias detected (p={p_bias:.4f})")
        if variance_inflated:
            print(f"    Variance inflated (p={p_levene:.4f})")
        print(f"    Edge Jaccard predicts noise floor ONLY for topologies that")
        print(f"    share structural ancestry. Walker calibration is mandatory")
        print(f"    for independently generated maps.")

    print(f"\n  PRACTICAL IMPLICATION:")
    if outcome == "GENERALIZES":
        print(f"    Any new topology can skip Walker calibration. Compute Edge")
        print(f"    Jaccard against a reference grid, plug into the regression,")
        print(f"    and get a noise floor estimate in milliseconds.")
    elif outcome == "BIASED_BUT_CORRECTABLE":
        print(f"    The relationship between Edge Jaccard and noise floor is real")
        print(f"    but the original Exp4 coefficients were biased by shared ancestry.")
        print(f"    Use the corrected pooled model for new topology pairs.")
        print(f"    Precision is moderate — use for rapid prototyping, not final")
        print(f"    calibration.")
    else:
        print(f"    Walker calibration (~1,010 sessions per variant) cannot be")
        print(f"    bypassed. Edge Jaccard is useful within a topology family")
        print(f"    (variants derived from the same parent) but not across")
        print(f"    independently generated topologies.")

    print(f"\n  All outputs saved to: {OUTPUT_DIR}/")
    print("=" * 78)

    return {
        "outcome": outcome,
        "exp4_r_sq": r_sq4,
        "pooled_r_sq": r_sq_p,
        "bias_p": p_bias,
        "levene_p": p_levene,
        "ancestry_significant": ancestry_significant,
        "slope4": slope4,
        "intercept4": intercept4,
        "slope_pooled": slope_p,
        "intercept_pooled": intercept_p,
    }


if __name__ == "__main__":
    main()
